### ISSUE TITLE
"The server has rejected the client credentials"

### ISSUE THREAD

**Issue by Qiangong2** [jimmy58663/pscredentialWithCert#2]
I'm trying to use your Get-SmartCardCred module, but unfortunately it is only partially working. When I try the following code:

```
$password = Get-SmartCardCred

Get-ADComputer -Credential "$password"  -Filter 'Name -like "DESK*"' -Properties IPv4Address | FT Name,IPv4Address -A
```

The smart card credential shows up which is great, but after it shows up the first time, a second standard `get-credential` prompt just shows up. When I can't select the admin cert on the second instance, it shows this:

```
Get-ADComputer : The server has rejected the client credentials.
At line:8 char:1
+ Get-ADComputer -Credential "$password"  -Filter 'Name -like "DESK*" ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [Get-ADComputer], AuthenticationException
    + FullyQualifiedErrorId : ActiveDirectoryCmdlet:System.Security.Authentication.AuthenticationException,Microsoft.ActiveDirectory.Management.Commands.GetADComputer
```
 
Any idea why it is showing up twice?

**Comment by jimmy58663** [comment]
I suspect the reason you are getting a second popup is because the Get-ADComputer cmdlet is not accepting the credential you provided and the credential your PowerShell session is running as does not have permissions either, so you are getting prompted for some credential.

This is odd to me as just looking up a computer account in AD should be able to be accomplished by a regular user account. However, a work around for what I am assuming is faulty logic in processing the credential by the cmdlet is to launch a PowerShell session with the smart card credentials and then run your commands from there without the need to save or specify a credential. The below code will launch a new PowerShell session with your saved smart card credential

```
$Cred = Get-SmartCardCred

$StartInfo = New-Object System.Diagnostics.ProcessStartInfo
$StartInfo.FileName = 'powershell.exe'
$StartInfo.UseShellExecute = $false
$StartInfo.UserName = $Cred.Username
$StartInfo.Password = $Cred.Password
$StartInfo.Arguments = 'Start-Process powershell'
$StartInfo.WorkingDirectory = $env:windir

$Process = New-Object System.Diagnostics.Process
$Process.StartInfo = $StartInfo
$Process.Start()

$Cred = $null
```

If for any reason you need an elevated prompt, you can change the Arguments to 'Start-Process powershell -verb runas'. Let me know if this works for you.

**Comment by Qiangong2** [comment]
After looking into it further, it seems like our organization has set up something unusual and that is causing the issue. I'll keep looking into it and update you if there's any change though.

Thanks for responding so fast!

**Comment by jimmy58663** [comment]
Closing because this appears to be an issue outside of this project's control.
